spring:
  application:
    name: back
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
#  output:
#    ansi:
#      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # 쿼리 보기 좋게 포맷
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.security: debug
jwt:
  secret: "this-is-a-very-long-secret-key-for-jwt-signing-minimum-256-bits" # 256비트 이상이어야 HS256 서명 가능
  access-expiration: 1800000   # 30분 (ms)

file:
  upload:
    dir: ${user.home}/triplog/uploadedimages
    base-url: ${FILE_UPLOAD_BASE_URL:http://localhost:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://192.168.0.5:3000}
